name: Run tests

on: [push, pull_request]

jobs:
    php-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    - php: 8.3
                    - php: 8.2
                    - php: 8.1

        name: PHP ${{ matrix.php }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Update composer
              run: composer self-update --2

            - name: Install dependencies
              run: composer install

            - name: Execute tests
              run: composer test
